2020-02-22 14:48:18,388 ERROR: Exception on / [GET] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 25, in index
    next_url = url_for('index', page=posts.next_num if posts.has_next() else None)
TypeError: 'bool' object is not callable
2020-02-22 14:48:48,150 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:29]
2020-02-22 15:05:35,069 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:29]
2020-02-22 15:06:14,790 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:29]
2020-02-22 15:21:39,960 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
2020-02-22 15:21:49,174 ERROR: Exception on /login [GET] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 45, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/arctickey/PycharmProjects/Blog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/arctickey/PycharmProjects/Blog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/arctickey/PycharmProjects/Blog/app/templates/login.html", line 26, in block "content"
    <p><a href="{{ url_for('reset_password_request') }}">Click to reset it!</a></p>
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2020-02-22 15:51:45,076 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
2020-02-22 15:51:49,343 ERROR: Exception on /reset_password_request [GET] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 154, in reset_password_request
    return render_template('reset_password_request.html',form=form,title='Password reset')
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/arctickey/PycharmProjects/Blog/app/templates/reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/arctickey/PycharmProjects/Blog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/arctickey/PycharmProjects/Blog/app/templates/reset_password_request.html", line 8, in block "content"
    {{ form.email.label }}<br>
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordRequestForm object' has no attribute 'email'
2020-02-22 15:52:36,543 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
